### PR TITLE
simplify part 2 and use larger verb trains

### PR DESCRIPTION
**Pull request by pitr**

### CODE REVIEW

**Comment by jitwit** [comment]
Perhaps you meant something like
```j
(>./ , [: {: (-.~ 1&+)) ids
```
? What's written is giving the wrong answer, though I do like the idea, it is simpler!

**Comment by pitr** [comment]
interesting that it doesn't work for you. Both work for me. I noticed that you use direct definitions in a few solutions, I am assuming you are running [J902 beta](https://code.jsoftware.com/wiki/System/ReleaseNotes/J902)? I don't see anything that would break my solution, and it works for me, both in J901 on my Mac and in j701 app on my iPhone.

Anywho, one of the ideas with my PR is to do away with using `[:`, since `([: f4 f3 f2 f1) a` results in `f4(f2(f3(a), f1(a)))`, but so does `(f3 f4@f2 f1) a`.

**Comment by jitwit** [comment]
edit: deleting previous remarks...

I thought there was a rank issue with `@`, but I actually realize it was sorting. If the maximal element is before the gap then `{.` gets `1+>./`, which is the case on my input where `{:` happens to give the right answer... I suppose the ids would need to be sorted for this to work, or the element greater than the max tallied out or something.

**Comment by jitwit** [comment]
oh and yes, I am using j902 beta mostly at the moment. It may be better for me to avoid direct definitions hah

**Comment by pitr** [comment]
ah, right you are. Didn't think of that case. I learned something today :) I guess the following is better:
```j
   ids =: 10 5 6 7 9
   (>./ , ] <./@-.~ 1&+) ids
10 8
```

**Comment by jitwit** [comment]
Right, `<./` is a nice way to resolve the problem! I just realized we can also get rid of the passive `~` by
```J 
>./ , 1&+ <./@-. ]
```

**Pull request merged**
